export enum ShipmentActionTypes {
    GET_SHIPMENT_DATA_LOADING = 'GET_SHIPMENT_DATA_LOADING',
    GET_SHIPMENT_DATA_SUCCESS = 'GET_SHIPMENT_DATA_SUCCESS',
    GET_SHIPMENT_DATA_FAILED = 'GET_SHIPMENT_DATA_FAILED',
}